### ISSUE TITLE
Do we need all these inference dependencies? 

### ISSUE THREAD

**Issue by PorkShoulderHolder** [miriamkw/GluPredKit#34]
- I see that the install script downloads tensorflow, keras, xgboost, and probably more.  
- I imagine these are probably used in some of the examples, but are these strictly necessary?  If the idea is for our library to be agnostic to what tools the user prefers, it should probably be more lightweight and not require you to download 250MB of code/data you do not need.  
- IRL use-case example:  I like PyTorch for DNNs, not tensorflow.  If I were to deploy this the build script is gonna be slowed down significantly by the tensorflow requirement even though im not going to use it.

**Comment by miriamkw** [comment]
Fixed in 6d672b2e5a76c99c52fa07f48bb5c31b1855a711
