### ISSUE TITLE
System dependencies

### ISSUE THREAD

**Issue by PorkShoulderHolder** [miriamkw/GluPredKit#60]
The python dependency mpi4py is either in requirements.txt or is needed by one of the other packages used, but the system wide Message Passing Interface requirements may not be there.

on Mac this is solved by doing `brew install mpich` before the install
on debian/linux this is solved by doing `sudo apt-get install libopenmpi-dev` before the install

It would be nice to automate this process for people installing the package via pypi - (or maybe you already have).

**Comment by miriamkw** [comment]
This is solved by adding it to the documentation because it's not supported to create an automatic solution with PyPi as far as I could see. The commands are also added to tests where it is necessary. It is the PyReplayBg dependency that requires the mpi4py, under the heavy dependencies.
